# Generated by Django 4.2.1 on 2024-01-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_orders_razorpay_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='oid',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amountpaid',
        ),
    ]
