# Generated by Django 4.2.1 on 2024-02-04 15:14

from django.db import migrations, models
import ecommerceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default=ecommerceapp.models.default_profile_picture, upload_to='images/profile_pics/'),
        ),
    ]
