# Generated by Django 4.2.1 on 2024-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
