# Generated by Django 4.2.1 on 2024-02-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_orderupdate_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='feedbackbool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='feedbackdesc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
