# Generated by Django 4.2.1 on 2024-02-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_orders_feedbackbool_orders_feedbackdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='feedbackrate',
            field=models.CharField(default='', max_length=5),
        ),
    ]
