# Generated by Django 4.2.1 on 2024-02-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_orders_feedbackrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='feedbackbool',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='feedbackdesc',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='feedbackrate',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='feedbackbool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='feedbackdesc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='feedbackrate',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='request_for_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.orders')),
                ('updateorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.orderupdate')),
            ],
        ),
    ]
